import { Link } from 'react-router-dom';
import { ArrowRight, Check, ChevronRight, MapPin, Phone, ShieldCheck, Star, Zap } from 'lucide-react';
import { serviceAreas, services, PHONE_DISPLAY, PHONE_TEL } from '@/data/site-data';
import SEO, { faqSchema, localBusinessSchema } from '@/components/SEO';
import CTASection from '@/components/CTASection';
import FAQAccordion from '@/components/FAQAccordion';

const areaFaqs = (city: string) => [
  { q: `What electrical services do you offer in ${city}?`, a: `Qualified Electric offers complete residential electrical services in ${city}, including electrical repair, panel upgrades, wiring, lighting installation, outlet and switch repair, EV charger installation, inspections, surge protection, and more.` },
  { q: `How quickly can you come to my ${city} home?`, a: `We offer same-day and next-day appointments throughout ${city} and the Denver metro area. Call us at (720) 794-0714 to check our availability.` },
  { q: 'Are your electricians licensed and insured?', a: 'Yes. Our electricians are fully licensed to work in Colorado and carry comprehensive insurance for your protection.' },
  { q: `Do you provide free estimates in ${city}?`, a: 'Yes, we provide upfront estimates for electrical projects. You will know the cost before any work begins.' },
];

export default function LocationPage({ slug }: { slug: string }) {
  const area = serviceAreas.find((item) => item.slug === slug) || serviceAreas[0];
  const faqs = areaFaqs(area.city);

  return (
    <>
      <SEO title={`Electrician in ${area.city}, ${area.state} | Qualified Electric`} description={area.metaDescription} canonical={`/${area.slug}`} schema={[localBusinessSchema, faqSchema(faqs)]} />
      <section className="relative pt-28 pb-20 lg:pt-40 lg:pb-28 bg-ink-950 overflow-hidden"><div className="absolute inset-0"><img src="https://images.pexels.com/photos/13633732/pexels-photo-13633732.jpeg?auto=compress&cs=tinysrgb&w=2000" alt={`${area.city}, Colorado skyline`} className="w-full h-full object-cover opacity-35" /><div className="absolute inset-0 bg-gradient-to-r from-ink-950 via-ink-950/85 to-ink-950/20" /><div className="absolute inset-0 bg-gradient-to-t from-ink-950 to-transparent" /></div><div className="absolute inset-0 bg-grid-dark bg-grid opacity-20" /><div className="container-pad relative"><nav className="flex items-center gap-2 text-sm text-ink-400 mb-8"><Link to="/" className="hover:text-electric-400">Home</Link><ChevronRight className="w-4 h-4" /><span className="text-ink-200">{area.city}, {area.state}</span></nav><div className="max-w-3xl"><span className="eyebrow-light"><span className="w-8 h-px bg-electric-400" /> Serving {area.city}, {area.state}</span><h1 className="text-5xl sm:text-6xl lg:text-7xl font-extrabold text-white leading-tight mt-5">Electrician in {area.city}, {area.state}</h1><p className="text-xl text-ink-200 leading-relaxed mt-6 max-w-2xl">{area.description} When you need a trusted local electrician, Qualified Electric is here to help.</p><div className="flex flex-col sm:flex-row gap-4 mt-8"><a href={`tel:${PHONE_TEL}`} className="btn-primary text-lg"><Phone className="w-5 h-5" /> Call {PHONE_DISPLAY}</a><a href="#services" className="btn-ghost-light text-lg">Our Services <ArrowRight className="w-5 h-5" /></a></div></div></div></section>

      <section className="py-20 lg:py-28 bg-white"><div className="container-pad"><div className="grid lg:grid-cols-[1.1fr_0.9fr] gap-12 lg:gap-20 items-center"><div><span className="eyebrow"><span className="w-8 h-px bg-electric-600" /> Your Local Electrician</span><h2 className="section-title mt-4">Reliable electrical service for {area.city} homeowners.</h2><div className="space-y-5 mt-6 text-ink-600 text-lg leading-relaxed"><p>When something goes wrong with your home\'s electrical system, you need a local electrician who responds quickly and does the job right. Qualified Electric proudly serves homeowners throughout {area.city} with safe, professional, code-compliant electrical work.</p><p>From an outlet that stopped working to a complete electrical panel upgrade, our experienced team brings clear communication and quality workmanship to every service call. We treat your home with the same care we\'d want for our own.</p></div><a href={`tel:${PHONE_TEL}`} className="btn-dark mt-8"><Phone className="w-4 h-4" /> Request Service</a></div><div className="rounded-3xl bg-ink-900 p-7 lg:p-9 text-white"><div className="w-14 h-14 rounded-2xl bg-electric-500 flex items-center justify-center mb-6"><MapPin className="w-7 h-7 text-ink-950" fill="currentColor" /></div><h3 className="font-display font-bold text-2xl">Serving {area.city} and beyond</h3><p className="text-ink-300 leading-relaxed mt-3">Our team provides residential electrical services throughout {area.city}, with convenient appointments and responsive support.</p><div className="space-y-3 mt-7 pt-6 border-t border-ink-700"><p className="flex items-center gap-3 text-sm text-ink-300"><ShieldCheck className="w-4 h-4 text-electric-400" /> Licensed & insured</p><p className="flex items-center gap-3 text-sm text-ink-300"><Check className="w-4 h-4 text-electric-400" /> Upfront pricing</p><p className="flex items-center gap-3 text-sm text-ink-300"><Star className="w-4 h-4 text-electric-400" fill="currentColor" /> Local service you can trust</p></div></div></div></div></section>

      <section id="services" className="py-20 lg:py-28 bg-ink-50"><div className="container-pad"><div className="max-w-3xl mb-12"><span className="eyebrow"><span className="w-8 h-px bg-electric-600" /> Services in {area.city}</span><h2 className="section-title mt-4">Complete home electrical services.</h2><p className="section-subtitle">Whatever your home needs, our electricians have the experience to handle it safely.</p></div><div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-5">{services.slice(0, 8).map((service) => <Link key={service.slug} to={`/${service.slug}`} className="group bg-white rounded-2xl p-6 border border-ink-100 hover:-translate-y-1 hover:shadow-xl hover:border-electric-300 transition-all duration-300"><div className="w-11 h-11 rounded-xl bg-electric-100 text-electric-700 flex items-center justify-center mb-5 group-hover:bg-electric-500 group-hover:text-ink-950 transition-colors"><Zap className="w-5 h-5" /></div><h3 className="font-display font-bold text-ink-900 group-hover:text-electric-700">{service.shortTitle}</h3><p className="text-sm text-ink-500 leading-relaxed mt-2 line-clamp-2">{service.description}</p><span className="inline-flex items-center gap-1 text-electric-600 font-bold text-sm mt-4">{service.shortTitle} <ArrowRight className="w-4 h-4" /></span></Link>)}</div></div></section>

      <section className="py-20 lg:py-28 bg-white"><div className="container-pad"><div className="grid lg:grid-cols-[0.8fr_1.2fr] gap-12 lg:gap-20"><div><span className="eyebrow"><span className="w-8 h-px bg-electric-600" /> FAQ</span><h2 className="section-title mt-4">Electrician questions, answered.</h2><p className="section-subtitle">Everything you need to know about electrical service in {area.city}.</p></div><FAQAccordion faqs={faqs} /></div></div></section>

      <CTASection title={`Need an electrician in ${area.city}?`} subtitle="Call Qualified Electric today for safe, reliable electrical service throughout the Denver metro." />
    </>
  );
}
